spring.application.name=demo
# H2 Database 記憶體資料庫設定
spring.datasource.url=jdbc:h2:mem:diarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 讓 Spring Boot 根據 Entity 自動建立資料表
spring.jpa.hibernate.ddl-auto=update

# 開啟 H2 控制台
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 在終端機顯示 SQL 語法
spring.jpa.show-sql=true